name: Sichtbarer Check

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node installieren
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Beispiel-Test
        run: |
          echo "Starte Beispiel-Test"
          echo "✅ Alles okay!"
