name: Sichtbarer Test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Sichtbarer Check
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonen
        uses: actions/checkout@v4

      - name: Node-Version prüfen
        run: node -v || echo "Node nicht installiert"
